function fig_hdl = PPGUI_build
% PPGUI_BUILD
%-------------------------------------------------------------------------------
% File name   : PPGUI_build.m
% Generated on: 31-Jul-2015 19:04:54
% Description :
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figure1;

%% ---------------------------------------------------------------------------
    function build_gui()
        % Creation of all uicontrols
        
        set(0,'defaultFigureColor',[1 1 1]);
        set(0,'DefaultAxesFontSize',8)
        set(0, 'DefaultTextColor', [0, 0, 0]);
        
        % Get size of screen in pixels
        set(0,'units','pixels')
        Pix_SS = get(0,'screensize');
        % Adjust display to these dimensions
        xmult = Pix_SS(3)/1920; % originally was on 1280x800 display, so need to adjust for current size NOTE: may not work well for displays smaller than a 13" Macbook w/o retina display
        ymult = Pix_SS(4)/1080;
        ppinv = [1*xmult 1*ymult 1*xmult 1*ymult];
        
        % --- FIGURE -------------------------------------
        handles.figure1 = figure( ...
            'Tag', 'figure1', ...
            'Units', 'characters', ...
            'Position', ppinv.*[100 8 202 70.8], ...
            'Name', 'PPGUI', ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off', ...
            'Color', [1 1 1]);
        
        % --- PANELS -------------------------------------
        handles.PANELTOP = uipanel( ...
            'Parent', handles.figure1, ...
            'Tag', 'PANELTOP', ...
            'Units', 'characters', ...
            'Position', ppinv.*[0 60 200 10], ...
            'BackgroundColor', [1 1 1], ...
            'Title', '', ...
            'ShadowColor', [1 1 1]);
        
        handles.PANELLEFT = uipanel( ...
            'Parent', handles.figure1, ...
            'Tag', 'PANELLEFT', ...
            'UserData', zeros(1,0), ...
            'Units', 'characters', ...
            'Position', ppinv.*[0 0 60 60], ...
            'BackgroundColor', [1 1 1], ...
            'Title', '', ...
            'ShadowColor', [1 1 1]);
        
        handles.PANELRIGHT = uipanel( ...
            'Parent', handles.figure1, ...
            'Tag', 'PANELRIGHT', ...
            'UserData', zeros(1,0), ...
            'Units', 'characters', ...
            'Position', ppinv.*[60 0 140 60], ...
            'BackgroundColor', [1 1 1], ...
            'Title', '', ...
            'ShadowColor', [1 1 1]);
        
        
        
        % --- STATIC TEXTS -------------------------------------
        handles.header1 = uicontrol( ...
            'Parent', handles.PANELTOP, ...
            'Tag', 'header1', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[50 5 100 2.5], ...
            'FontAngle', 'oblique', ...
            'FontSize', 14, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'SRA Post-Processor');
        
        handles.header2 = uicontrol( ...
            'Parent', handles.PANELTOP, ...
            'Tag', 'header2', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[50 3 100 2.5], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Created by Nicole Paul');
        
        handles.thdata = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[2.6 58.6 30 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Time History Data:', ...
            'HorizontalAlignment', 'left');
        
        handles.rsdata = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[2.8 36 30 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Response Spectrum Data:', ...
            'HorizontalAlignment', 'left');
        
        handles.ppdata = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'ppdata', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[2.8 17 30 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Peak Profile Data:', ...
            'HorizontalAlignment', 'left');
        
        handles.hdata = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'hdata', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[2.8 7 30 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Hysteresis Data:', ...
            'HorizontalAlignment', 'left');
        
        handles.text30 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'text30', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.4 33.8 10 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Damping:', ...
            'HorizontalAlignment', 'left');
        
        handles.text7 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text7', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 56 30.8 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Number of folders in directory:', ...
            'HorizontalAlignment', 'left');
        
        handles.nfolders = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'nfolders', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[38.4 55.9 30.8 1.5], ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'N/A', ...
            'HorizontalAlignment', 'left');
        
        handles.text9 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text9', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6 53.4 30 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Legend Names:', ...
            'HorizontalAlignment', 'left');
        
        handles.text10 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text10', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 51.1 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 1:', ...
            'HorizontalAlignment', 'left');
        
        handles.text11 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text11', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[69.6 53 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Color', ...
            'HorizontalAlignment', 'left');
        
        handles.text12 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text12', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 52.9 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Line Type', ...
            'HorizontalAlignment', 'left');
        
        handles.text14 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text14', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 48.8 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 2:', ...
            'HorizontalAlignment', 'left');
        
        handles.text15 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text15', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 46.5 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 3:', ...
            'HorizontalAlignment', 'left');
        
        handles.text16 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text16', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 44.2 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 4:', ...
            'HorizontalAlignment', 'left');
        
        handles.text17 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text17', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 41.8 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 5:', ...
            'HorizontalAlignment', 'left');
        
        handles.text18 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text18', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 39.5 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 6:', ...
            'HorizontalAlignment', 'left');
        
        handles.text19 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text19', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 37.2 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 7:', ...
            'HorizontalAlignment', 'left');
        
        handles.text20 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text20', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 34.9 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 8:', ...
            'HorizontalAlignment', 'left');
        
        handles.text21 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text21', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 32.6 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 9:', ...
            'HorizontalAlignment', 'left');
        
        handles.text22 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text22', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 30.3 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 10:', ...
            'HorizontalAlignment', 'left');
        
        handles.text23 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text23', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 28 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 11:', ...
            'HorizontalAlignment', 'left');
        
        handles.text24 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text24', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 25.7 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Folder 12:', ...
            'HorizontalAlignment', 'left');
        
        handles.text27 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text27', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[5.4 21 40 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Response Spectrum Calculations:', ...
            'HorizontalAlignment', 'left');
        
        handles.text28 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text28', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[54 21 40 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Peak Profile Calculations:', ...
            'HorizontalAlignment', 'left');
        
        handles.text29 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text29', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[4.8 10.9 40 1.2], ...
            'FontAngle', 'oblique', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Unit Conversions:', ...
            'HorizontalAlignment', 'left');
        
        handles.text31 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text31', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[5.4 8.7 15 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Acceleration:', ...
            'HorizontalAlignment', 'right');
        
        handles.text32 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text32', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[38.2 8.7 10 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Velocity:', ...
            'HorizontalAlignment', 'right');
        
        handles.text33 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text33', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[64.2 8.7 15 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Displacement:', ...
            'HorizontalAlignment', 'right');
        
        handles.text34 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text34', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[95 8.7 10 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Stress:', ...
            'HorizontalAlignment', 'right');
        
        handles.text35 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'text35', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', ppinv.*[53 55.8 20 1.5], ...
            'FontWeight', 'light', ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Analysis Set Title:', ...
            'HorizontalAlignment', 'left');
        
        % --- PUSHBUTTONS -------------------------------------
        handles.opendirectory = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'opendirectory', ...
            'UserData', zeros(1,0), ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', ppinv.*[38 58 10 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Open', ...
            'CData', zeros(1,0), ...
            'Callback', @opendirectory_Callback);
        
        handles.generatefig = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'generatefig', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', ppinv.*[32.8 2.7 19 1.8], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Generate Figures', ...
            'Callback', @generatefig_Callback);
        
        handles.generatecsv = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'generatecsv', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', ppinv.*[54.8 2.7 19 1.8], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Generate CSVs', ...
            'Callback', @generatecsv_Callback);
        
        handles.generatemat = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'generatemat', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', ppinv.*[76.8 2.7 19 1.8], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Generate MATs', ...
            'Callback', @generatemat_Callback);
        
        handles.loadpresets = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'loadpresets', ...
            'UserData', zeros(1,0), ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', ppinv.*[58 58 20 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Load Presets', ...
            'CData', zeros(1,0), ...
            'Callback', @loadpresets_Callback);
        
        handles.savepresets = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'savepresets', ...
            'UserData', zeros(1,0), ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', ppinv.*[79.4 58 20 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Save Presets', ...
            'CData', zeros(1,0), ...
            'Callback', @savepresets_Callback);
        
        % --- CHECKBOXES -------------------------------------
        handles.thdata1 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata1', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 56.6 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Surface Acceleration');
        
        handles.thdata2 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata2', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 55 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Surface Velocity');
        
        handles.thdata3 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata3', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 53.4 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Surface Displacement');
        
        handles.thdata4 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata4', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 51.8 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Bedrock (Outcrop) Acceleration');
        
        handles.thdata5 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata5', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 50.2 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Bedrock (Outcrop) Velocity');
        
        handles.thdata6 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata6', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 48.6 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Bedrock (Outcrop) Displacement');
        
        handles.thdata7 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata7', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 47 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Strain Rate @ Layer');
        
        handles.thdata8 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thdata8', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.4 43 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Acceleration @ Depth');
        
        handles.rsdata1 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata1', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 32.5 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Surface Acceleration');
        
        handles.rsdata2 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata2', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 30.8 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Bedrock (Infield) Acceleration');
        
        handles.rsdata3 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata3', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 29.2 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Bedrock (Outcrop) Acceleration');
        
        handles.rsdata4 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata4', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 27.6 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Spectral Amplified (Surface/Bedrock)');
        
        handles.rsdata5 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata5', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 26 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Surface Displacement');
        
        handles.rsdata6 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdata6', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.2 24.4 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Acceleration @ Depth');
        
        handles.ppdata1 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'ppdata1', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3 15.2 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Shear Strain');
        
        handles.ppdata2 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'ppdata2', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3 13.5 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Shear Stress');
        
        handles.ppdata3 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'ppdata3', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3 11.8 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Acceleration');
        
        handles.ppdata4 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'ppdata4', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3 10.1 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Strain Rate');
        
        handles.hdata1 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'hdata1', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[2.8 5.5 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Specified Layers');
        
        
        handles.rsmean = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'rsmean', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 19.2 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Mean');
        
        handles.rsmax = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'rsmax', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 17.6 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Max');
        
        handles.rsmeanstd = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'rsmeanstd', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.2 16 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Mean +/- # St. Dev.');
        
        handles.ppmean = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'ppmean', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[54.8 19.2 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Mean');
        
        handles.ppmax = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'ppmax', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[54.8 17.6 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Max');
        
        handles.ppmeanstd = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'ppmeanstd', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[54.8 16 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Mean +/- # St. Dev.');
        
        handles.rsmajor = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'rsmajor', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.4 14.3 50 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Major/Minor');
        
        % --- EDIT TEXTS -------------------------------------
        handles.rsdamping = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsdamping', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[13.4 34 10 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', '0.05');
        
        handles.directorystr = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'directorystr', ...
            'UserData', zeros(1,0), ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6 58 30.8 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Choose Directory Location ...', ...
            'HorizontalAlignment', 'left');
        
        handles.f1name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f1name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 51.4 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 1', ...
            'HorizontalAlignment', 'left');
        
        handles.f2name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f2name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 49.1 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 2', ...
            'HorizontalAlignment', 'left');
        
        handles.f3name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f3name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 46.8 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 3', ...
            'HorizontalAlignment', 'left');
        
        handles.f4name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f4name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 44.5 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 4', ...
            'HorizontalAlignment', 'left');
        
        handles.f5name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f5name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 42.2 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 5', ...
            'HorizontalAlignment', 'left');
        
        handles.f6name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f6name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 39.8 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 6', ...
            'HorizontalAlignment', 'left');
        
        handles.f7name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f7name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 37.6 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 7', ...
            'HorizontalAlignment', 'left');
        
        handles.f8name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f8name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 35.2 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 8', ...
            'HorizontalAlignment', 'left');
        
        handles.f9name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f9name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 32.9 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 9', ...
            'HorizontalAlignment', 'left');
        
        handles.f10name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f10name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 30.6 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 10', ...
            'HorizontalAlignment', 'left');
        
        handles.f11name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f11name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 28.3 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 11', ...
            'HorizontalAlignment', 'left');
        
        handles.f12name = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f12name', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[16.4 26 50 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Data Set 12', ...
            'HorizontalAlignment', 'left');
        
        handles.rsstd = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'rsstd', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[29.6 16 6 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', '1');
        
        handles.ppstd = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'ppstd', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[78.2 16 6 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', '1');
        
        handles.analysisname = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'analysisname', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', ppinv.*[71.4 56.1 27.6 1.5], ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.502 0.502 0.502], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Analysis Suite 1', ...
            'HorizontalAlignment', 'left');
        
        % --- LISTBOXES -------------------------------------
        handles.rsabox = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'rsabox', ...
            'Style', 'listbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.6 20.2 25 4], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Select directory...');
        
        handles.hbox = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'hbox', ...
            'Style', 'listbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[6.6 1.5 25 4], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Select directory...');
        
        handles.thabox = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thabox', ...
            'Style', 'listbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.8 38.8 25 4], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Select directory...');
        
        handles.thabox2 = uicontrol( ...
            'Parent', handles.PANELLEFT, ...
            'Tag', 'thabox2', ...
            'Style', 'listbox', ...
            'Units', 'characters', ...
            'Position', ppinv.*[3.8 44.5 25 4], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Select directory...');
        
        % --- POPUP MENU -------------------------------------
        handles.f1color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f1color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 51.4 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f1line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f1line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 51.4 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f2color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f2color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 49.1 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f2line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f2line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 49.1 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f3color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f3color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 46.8 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 3, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.fline3 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'fline3', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 46.8 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f4color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f4color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 44.5 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 4, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.fline4 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'fline4', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 44.5 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f5color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f5color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 42.2 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 5, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.fline5 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'fline5', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 42.2 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f6color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f6color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 39.8 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 6, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.fline6 = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'fline6', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 39.8 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f7color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f7color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 37.5 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f7line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f7line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 37.5 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f8color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f8color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 35.2 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f8line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f8line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 35.2 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f9color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f9color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 32.9 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 3, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f9line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f9line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 32.9 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f10color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f10color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 30.6 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 4, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f10line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f10line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 30.6 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f11color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f11color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 28.3 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 5, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f11line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f11line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 28.3 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.f12color = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f12color', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[70 26 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 6, ...
            'String', {'r','g','b','m','c','y','k'});
        
        handles.f12line = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'f12line', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[84.8 26 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'Value', 2, ...
            'String', {'-','--','-.','--.','.-','*-','^-','v-','o-','s-','.--','*--','^--','v--','o--','s--',':'});
        
        handles.aunits = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'aunits', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[21 9 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'g','m/s^2'});
        
        handles.vunits = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'vunits', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[49 9 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'cm/s','m/s'});
        
        handles.dunits = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'dunits', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[80 9 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'cm','m'});
        
        handles.sigunits = uicontrol( ...
            'Parent', handles.PANELRIGHT, ...
            'Tag', 'sigunits', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', ppinv.*[105.8 9 12 1.5], ...
            'BackgroundColor', [1 1 1], ...
            'String', {'kPa','Pa'});
        
        % --- AXES -------------------------------------
        handles.banneraxes = axes( ...
            'Parent', handles.PANELTOP, ...
            'Tag', 'logoaxes', ...
            'Units', 'characters', ...
            'Position', ppinv.*[4 4.5 30 3]);
        
        % Arup logo
        banner = imread('logo.png');
        image(banner, 'Parent', handles.banneraxes);
        set(gca, 'Visible', 'off');
        
        
        
    end

%% ---------------------------------------------------------------------------
    function opendirectory_Callback(hObject,evendata) %#ok<INUSD>
        
        % Find directory
        datafile = uigetdir;
        set(handles.directorystr, 'str', datafile);
        [~, name] = fileparts(datafile);
        
        % Update analysis suite name based off directory name
        set(handles.analysisname, 'str', name);
        
        % Determine number of folders and update count
        FileList = dir(datafile);
        FileList = FileList(arrayfun(@(x) x.name(1), FileList) ~= '.');
        N = size(FileList, 1);
        if ~exist(fullfile(datafile,'PROCESSED_DATA.mat'),'file');
            nfolders = N;
            FileList = FileList(1:end);
        else
            nfolders = N - 1;
            FileList = FileList(1:end-1);
        end
        
        set(handles.nfolders, 'str', num2str(nfolders));
        
        % If number of folders exceeds 12, give warning message
        if nfolders > 12
            warning('myfun:fexceed','SRA Post-Processer will only process first 12 folders');
            set(handles.nfolders, 'ForegroundColor', 'r');
        end
        
        % Load legend names for each folder
        for i = 1:min(nfolders,12)
            fieldi = strcat('f',num2str(i),'name');
            set(handles.(fieldi), 'str', FileList(i).name);
            set(handles.(fieldi), 'BackgroundColor', [1 1 1]);
        end
        
        % Grey out unnecessary legend names
        if nfolders < 12
            set(handles.nfolders, 'ForegroundColor', 'k');
            for i = nfolders+1:12
                fieldi = strcat('f',num2str(i),'name');
                set(handles.(fieldi), 'BackgroundColor', [0.8 0.8 0.8]);
                set(handles.(fieldi), 'str', '');
            end
        end
        
        % Run data processing
        
        % Update listboxes for available depths and layers
        
    end

%% ---------------------------------------------------------------------------
    function generatefig_Callback(hObject,evendata) %#ok<INUSD>

        % Changing default figure properties
        set(0,'defaultFigureColor',[1 1 1]);
        set(0,'DefaultAxesFontSize',10)
        
        % Handle inputs
        [convf, unitstr] = handleinputs;
        directorystr = get(handles.directorystr, 'str');
        
        % Process data
        if ~exist(fullfile(directorystr,'PROCESSED_DATA.mat'),'file'); % Create data structures if does not exist yet
            [NDAT, SDAT, nprofile, ncase] = processData(directorystr);
        else
            load(fullfile(directorystr,'PROCESSED_DATA.mat')); % Load data structures if already exists
        end
        
        % Setting count of folders
        nfolders = str2double(get(handles.nfolders,'str'));
        
        % Getting folder ("earthquake") names
        eqname = cell(nfolders,1);
        for i = 1:nfolders
            fieldi = strcat('f',num2str(i),'name');
            eqname{i} = get(handles.(fieldi),'str');
        end
        
        
        %% TIME HISTORY DATA
        
        % TH1
        if get(handles.thdata1,'Value')
            plot_timeHistory(NDAT, 'ax', 'ay', eqname, 'Surface Acceleration', 1, convf, unitstr, 1, nprofile, ncase);
        end
        
        % TH 2
        
        if get(handles.thdata2,'Value')
            plot_timeHistory(NDAT, 'vx', 'vy', eqname, 'Surface Velocity', 2, convf, unitstr, 1, nprofile, ncase);
        end
        
        
        % TH 3
        if get(handles.thdata3,'Value')
            plot_timeHistory(NDAT, 'dx','dy', eqname, 'Surface Displacement', 3,  convf, unitstr, 1, nprofile, ncase);
        end
        
        % TH 4
        if get(handles.thdata4,'Value')
            plot_timeHistory(NDAT, 'ax', 'ay', eqname, 'Bedrock (Infield) Acceleration', 1, convf, unitstr, 0, nprofile, ncase);
        end
        
        % TH 5
        if get(handles.thdata5,'Value')
            plot_timeHistory(NDAT, 'vx', 'vy', eqname,'Bedrock (Infield) Velocity', 2, convf, unitstr, 0, nprofile, ncase);
        end
        
        
        %% RESPONSE SPECTRUM DATA
        
        % Find necessary calculations
        calc_rs1 = get(handles.rsmean, 'Value');
        calc_rs2 = get(handles.rsmax, 'Value');
        calc_rs3 = get(handles.rsmeanstd, 'Value');
        calc_rs4 = get(handles.rsmajor, 'Value');
        calc_rs5 = str2double(get(handles.rsstd, 'str'));
        rs_bool = [calc_rs1 calc_rs2 calc_rs3 calc_rs4 calc_rs5];
        
        
        % RS
        E = str2double(get(handles.rsdamping,'str'));
        
        % RS 1
        if get(handles.rsdata1,'Value')
            plot_responseSpectrum(NDAT, E, unitstr, convf, eqname,'Surface Response Spectrum', 1, nprofile, ncase, rs_bool);
        end
        
        
        % RS 2
        if get(handles.rsdata2,'Value')
            plot_responseSpectrum(NDAT, E, unitstr, convf, eqname,'Bedrock (Infield) Response Spectrum', 2, nprofile, ncase, rs_bool);
        end
        
        
        % RS 3
        if get(handles.rsdata3,'Value') % TEMP - No outcrop yet
            plot_responseSpectrum(NDAT, E, unitstr, convf, eqname,'Bedrock (Infield) Response Spectrum', 3, nprofile, ncase, rs_bool);
        end
        
        % RS 4
        if get(handles.rsdata4,'Value')
            plot_responseSpectrum(NDAT, E, unitstr, convf, eqname,'Spectral Amplification', 4, nprofile, ncase, rs_bool);
        end
        
        
        %% PEAK PROFILE DATA
        
        % Find necessary calculations
        calc_pp1 = get(handles.ppmean, 'Value');
        calc_pp2 = get(handles.ppmax, 'Value');
        calc_pp3 = get(handles.ppmeanstd, 'Value');
        calc_pp4 = str2double(get(handles.ppstd, 'str'));
        pp_bool = [calc_pp1 calc_pp2 calc_pp3 calc_pp4];
        
        
        % PP 1
        if get(handles.ppdata1, 'Value')
            plot_peakProfile(SDAT, 'epsyz', 'epszx', eqname, 'Max Shear Strain', 5, convf, unitstr, nprofile, ncase, pp_bool)
        end
        
        
        
        
        
    end

%% ---------------------------------------------------------------------------
    function generatecsv_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function generatemat_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function loadpresets_Callback(hObject,evendata) %#ok<INUSD>
        
        datafile = getfilename;
        mydata = load(datafile, 'handles');
        
        % Load appropriate data
        
    end

%% ---------------------------------------------------------------------------
    function savepresets_Callback(hObject,evendata) %#ok<INUSD>
        
        % Store presets
        
        [file, path] = uiputfile(fullfile('Presets','*.mat'), 'Choose preset name...');
        save(fullfile(path,file), 'variables');
        
        
    end

%% ---------------------------------------------------------------------------

    function [convf, unitstr] = handleinputs
        
        % Unit conversion factors
        if get(handles.aunits, 'Value')
            aconv = 1/9.81;
            astr = 'g';
        else
            aconv = 1;
            astr = 'm/s^2';
        end
        if get(handles.vunits, 'Value')
            vconv = 1e2;
            vstr = 'cm/s';
        else
            vconv = 1;
            vstr = 'm/s';
        end
        if get(handles.dunits, 'Value')
            dconv = 1e2;
            dstr = 'cm';
        else
            dconv = 1;
            dstr = 'm';
        end
        if get(handles.sigunits, 'Value')
            sigconv = 1e-3;
            sigstr = 'kPa';
        else
            sigconv = 1;
            sigstr = 'Pa';
        end
        epsconv = 2e2; % NOTE: 2 is to convert to engineering strain, e2 to %
        epsstr = '%';
        
        convf = [aconv vconv dconv sigconv epsconv];
        unitstr = {astr, vstr, dstr, sigstr, epsstr};
        
        % Determine which data is requested
        
        % Determine column header (legend) data
        
        
        
        
    end


end
